"""Standard filament profile constants and defaults.

This module contains the standard filament profile keys and their default values
derived from OrcaSlicer's built-in filament templates.

Template Version: OrcaSlicer 2.3.1
Last Updated: 2025-12-29

The templates were extracted from OrcaSlicer 2.3.1 release and define 58 standard
filament profile keys. When flattening profiles, missing keys are populated with
material-type-appropriate defaults from the corresponding template.

See: https://github.com/SoftFever/OrcaSlicer/releases/tag/v2.3.1
"""

# Material type to template defaults mapping
# Keys are filament types as they appear in profiles
# Values are dictionaries of all 58 standard keys with their defaults
FILAMENT_MATERIAL_DEFAULTS = {
    "ABS": {
        "activate_air_filtration": ["1"],
        "chamber_temperatures": ["0"],
        "close_fan_the_first_x_layers": ["3"],
        "compatible_printers": [],
        "complete_print_exhaust_fan_speed": ["70"],
        "cool_plate_temp": ["0"],
        "cool_plate_temp_initial_layer": ["0"],
        "during_print_exhaust_fan_speed": ["70"],
        "eng_plate_temp": ["90"],
        "eng_plate_temp_initial_layer": ["90"],
        "fan_cooling_layer_time": ["30"],
        "fan_max_speed": ["80"],
        "fan_min_speed": ["10"],
        "filament_cost": ["20"],
        "filament_density": ["1.04"],
        "filament_deretraction_speed": ["nil"],
        "filament_diameter": ["1.75"],
        "filament_end_gcode": ["; filament end gcode \nM106 P3 S0\n"],
        "filament_flow_ratio": ["1"],
        "filament_is_support": ["0"],
        "filament_max_volumetric_speed": ["28.6"],
        "filament_minimal_purge_on_wipe_tower": ["15"],
        "filament_retract_before_wipe": ["nil"],
        "filament_retract_restart_extra": ["nil"],
        "filament_retract_when_changing_layer": ["nil"],
        "filament_retraction_length": ["nil"],
        "filament_retraction_minimum_travel": ["nil"],
        "filament_retraction_speed": ["nil"],
        "filament_settings_id": [""],
        "filament_soluble": ["0"],
        "filament_start_gcode": ["; Filament gcode\n{if activate_air_filtration[current_extruder] && support_air_filtration}\nM106 P3 S{during_print_exhaust_fan_speed_num[current_extruder]} \n{endif}"],
        "filament_type": ["ABS"],
        "filament_vendor": ["Generic"],
        "filament_wipe": ["nil"],
        "filament_wipe_distance": ["nil"],
        "filament_z_hop": ["nil"],
        "filament_z_hop_types": ["nil"],
        "full_fan_speed_layer": ["0"],
        "hot_plate_temp": ["90"],
        "hot_plate_temp_initial_layer": ["90"],
        "instantiation": "false",
        "name": "Generic ABS template",
        "nozzle_temperature": ["270"],
        "nozzle_temperature_initial_layer": ["260"],
        "nozzle_temperature_range_high": ["280"],
        "nozzle_temperature_range_low": ["240"],
        "overhang_fan_speed": ["80"],
        "overhang_fan_threshold": ["25%"],
        "reduce_fan_stop_start_freq": ["1"],
        "required_nozzle_HRC": ["3"],
        "slow_down_for_layer_cooling": ["1"],
        "slow_down_layer_time": ["3"],
        "slow_down_min_speed": ["20"],
        "temperature_vitrification": ["100"],
        "textured_plate_temp": ["90"],
        "textured_plate_temp_initial_layer": ["90"],
        "type": "filament",
    },
    "ASA": {
        "activate_air_filtration": ["1"],
        "chamber_temperatures": ["0"],
        "close_fan_the_first_x_layers": ["3"],
        "compatible_printers": [],
        "complete_print_exhaust_fan_speed": ["70"],
        "cool_plate_temp": ["0"],
        "cool_plate_temp_initial_layer": ["0"],
        "during_print_exhaust_fan_speed": ["70"],
        "eng_plate_temp": ["90"],
        "eng_plate_temp_initial_layer": ["90"],
        "fan_cooling_layer_time": ["35"],
        "fan_max_speed": ["80"],
        "fan_min_speed": ["10"],
        "filament_cost": ["20"],
        "filament_density": ["1.04"],
        "filament_deretraction_speed": ["nil"],
        "filament_diameter": ["1.75"],
        "filament_end_gcode": ["; filament end gcode \nM106 P3 S0\n"],
        "filament_flow_ratio": ["1"],
        "filament_is_support": ["0"],
        "filament_max_volumetric_speed": ["28.6"],
        "filament_minimal_purge_on_wipe_tower": ["15"],
        "filament_retract_before_wipe": ["nil"],
        "filament_retract_restart_extra": ["nil"],
        "filament_retract_when_changing_layer": ["nil"],
        "filament_retraction_length": ["nil"],
        "filament_retraction_minimum_travel": ["nil"],
        "filament_retraction_speed": ["nil"],
        "filament_settings_id": [""],
        "filament_soluble": ["0"],
        "filament_start_gcode": ["; Filament gcode\n{if activate_air_filtration[current_extruder] && support_air_filtration}\nM106 P3 S{during_print_exhaust_fan_speed_num[current_extruder]} \n{endif}"],
        "filament_type": ["ASA"],
        "filament_vendor": ["Generic"],
        "filament_wipe": ["nil"],
        "filament_wipe_distance": ["nil"],
        "filament_z_hop": ["nil"],
        "filament_z_hop_types": ["nil"],
        "full_fan_speed_layer": ["0"],
        "hot_plate_temp": ["90"],
        "hot_plate_temp_initial_layer": ["90"],
        "instantiation": "false",
        "name": "Generic ASA template",
        "nozzle_temperature": ["260"],
        "nozzle_temperature_initial_layer": ["260"],
        "nozzle_temperature_range_high": ["280"],
        "nozzle_temperature_range_low": ["240"],
        "overhang_fan_speed": ["80"],
        "overhang_fan_threshold": ["25%"],
        "reduce_fan_stop_start_freq": ["1"],
        "required_nozzle_HRC": ["3"],
        "slow_down_for_layer_cooling": ["1"],
        "slow_down_layer_time": ["3"],
        "slow_down_min_speed": ["20"],
        "temperature_vitrification": ["100"],
        "textured_plate_temp": ["90"],
        "textured_plate_temp_initial_layer": ["90"],
        "type": "filament",
    },
    "HIPS": {
        "activate_air_filtration": ["0"],
        "additional_cooling_fan_speed": ["0"],
        "chamber_temperatures": ["0"],
        "close_fan_the_first_x_layers": ["3"],
        "compatible_printers": [],
        "complete_print_exhaust_fan_speed": ["70"],
        "cool_plate_temp": ["0"],
        "cool_plate_temp_initial_layer": ["0"],
        "during_print_exhaust_fan_speed": ["70"],
        "eng_plate_temp": ["90"],
        "eng_plate_temp_initial_layer": ["90"],
        "fan_cooling_layer_time": ["10"],
        "fan_max_speed": ["60"],
        "fan_min_speed": ["0"],
        "filament_cost": ["22.99"],
        "filament_density": ["1.06"],
        "filament_deretraction_speed": ["nil"],
        "filament_diameter": ["1.75"],
        "filament_end_gcode": ["; filament end gcode \nM106 P3 S0\n"],
        "filament_flow_ratio": ["1"],
        "filament_is_support": ["0"],
        "filament_max_volumetric_speed": ["8"],
        "filament_minimal_purge_on_wipe_tower": ["15"],
        "filament_retract_before_wipe": ["nil"],
        "filament_retract_restart_extra": ["nil"],
        "filament_retract_when_changing_layer": ["nil"],
        "filament_retraction_length": ["nil"],
        "filament_retraction_minimum_travel": ["nil"],
        "filament_retraction_speed": ["nil"],
        "filament_settings_id": [""],
        "filament_soluble": ["0"],
        "filament_start_gcode": ["; Filament gcode\n{if activate_air_filtration[current_extruder] && support_air_filtration}\nM106 P3 S{during_print_exhaust_fan_speed_num[current_extruder]} \n{endif}"],
        "filament_type": ["HIPS"],
        "filament_vendor": ["Generic"],
        "filament_wipe": ["nil"],
        "filament_wipe_distance": ["nil"],
        "filament_z_hop": ["nil"],
        "filament_z_hop_types": ["nil"],
        "full_fan_speed_layer": ["0"],
        "hot_plate_temp": ["90"],
        "hot_plate_temp_initial_layer": ["90"],
        "instantiation": "false",
        "name": "Generic HIPS template",
        "nozzle_temperature": ["240"],
        "nozzle_temperature_initial_layer": ["240"],
        "nozzle_temperature_range_high": ["270"],
        "nozzle_temperature_range_low": ["220"],
        "overhang_fan_speed": ["80"],
        "overhang_fan_threshold": ["25%"],
        "reduce_fan_stop_start_freq": ["0"],
        "required_nozzle_HRC": ["3"],
        "slow_down_for_layer_cooling": ["1"],
        "slow_down_layer_time": ["6"],
        "slow_down_min_speed": ["20"],
        "temperature_vitrification": ["100"],
        "textured_plate_temp": ["90"],
        "textured_plate_temp_initial_layer": ["90"],
        "type": "filament",
    },
    "PA": {
        "activate_air_filtration": ["1"],
        "chamber_temperatures": ["0"],
        "close_fan_the_first_x_layers": ["3"],
        "compatible_printers": [],
        "complete_print_exhaust_fan_speed": ["70"],
        "cool_plate_temp": ["0"],
        "cool_plate_temp_initial_layer": ["0"],
        "during_print_exhaust_fan_speed": ["70"],
        "eng_plate_temp": ["100"],
        "eng_plate_temp_initial_layer": ["100"],
        "fan_cooling_layer_time": ["4"],
        "fan_max_speed": ["60"],
        "fan_min_speed": ["0"],
        "filament_cost": ["20"],
        "filament_density": ["1.04"],
        "filament_deretraction_speed": ["nil"],
        "filament_diameter": ["1.75"],
        "filament_end_gcode": ["; filament end gcode \nM106 P3 S0\n"],
        "filament_flow_ratio": ["1"],
        "filament_is_support": ["0"],
        "filament_max_volumetric_speed": ["8"],
        "filament_minimal_purge_on_wipe_tower": ["15"],
        "filament_retract_before_wipe": ["nil"],
        "filament_retract_restart_extra": ["nil"],
        "filament_retract_when_changing_layer": ["nil"],
        "filament_retraction_length": ["nil"],
        "filament_retraction_minimum_travel": ["nil"],
        "filament_retraction_speed": ["nil"],
        "filament_settings_id": [""],
        "filament_soluble": ["0"],
        "filament_start_gcode": ["; Filament gcode\n{if activate_air_filtration[current_extruder] && support_air_filtration}\nM106 P3 S{during_print_exhaust_fan_speed_num[current_extruder]} \n{endif}"],
        "filament_type": ["PA"],
        "filament_vendor": ["Generic"],
        "filament_wipe": ["nil"],
        "filament_wipe_distance": ["nil"],
        "filament_z_hop": ["nil"],
        "filament_z_hop_types": ["nil"],
        "full_fan_speed_layer": ["0"],
        "hot_plate_temp": ["100"],
        "hot_plate_temp_initial_layer": ["100"],
        "instantiation": "false",
        "name": "Generic PA template",
        "nozzle_temperature": ["290"],
        "nozzle_temperature_initial_layer": ["290"],
        "nozzle_temperature_range_high": ["300"],
        "nozzle_temperature_range_low": ["260"],
        "overhang_fan_speed": ["30"],
        "overhang_fan_threshold": ["95%"],
        "reduce_fan_stop_start_freq": ["0"],
        "required_nozzle_HRC": ["40"],
        "slow_down_for_layer_cooling": ["1"],
        "slow_down_layer_time": ["2"],
        "slow_down_min_speed": ["20"],
        "temperature_vitrification": ["108"],
        "textured_plate_temp": ["100"],
        "textured_plate_temp_initial_layer": ["100"],
        "type": "filament",
    },
    "PC": {
        "activate_air_filtration": ["0"],
        "chamber_temperatures": ["0"],
        "close_fan_the_first_x_layers": ["3"],
        "compatible_printers": [],
        "complete_print_exhaust_fan_speed": ["70"],
        "cool_plate_temp": ["0"],
        "cool_plate_temp_initial_layer": ["0"],
        "during_print_exhaust_fan_speed": ["70"],
        "eng_plate_temp": ["110"],
        "eng_plate_temp_initial_layer": ["110"],
        "fan_cooling_layer_time": ["30"],
        "fan_max_speed": ["60"],
        "fan_min_speed": ["10"],
        "filament_cost": ["20"],
        "filament_density": ["1.04"],
        "filament_deretraction_speed": ["nil"],
        "filament_diameter": ["1.75"],
        "filament_end_gcode": ["; filament end gcode \nM106 P3 S0\n"],
        "filament_flow_ratio": ["1"],
        "filament_is_support": ["0"],
        "filament_max_volumetric_speed": ["23.2"],
        "filament_minimal_purge_on_wipe_tower": ["15"],
        "filament_retract_before_wipe": ["nil"],
        "filament_retract_restart_extra": ["nil"],
        "filament_retract_when_changing_layer": ["nil"],
        "filament_retraction_length": ["nil"],
        "filament_retraction_minimum_travel": ["nil"],
        "filament_retraction_speed": ["nil"],
        "filament_settings_id": [""],
        "filament_soluble": ["0"],
        "filament_start_gcode": ["; Filament gcode\n{if activate_air_filtration[current_extruder] && support_air_filtration}\nM106 P3 S{during_print_exhaust_fan_speed_num[current_extruder]} \n{endif}"],
        "filament_type": ["PC"],
        "filament_vendor": ["Generic"],
        "filament_wipe": ["nil"],
        "filament_wipe_distance": ["nil"],
        "filament_z_hop": ["nil"],
        "filament_z_hop_types": ["nil"],
        "full_fan_speed_layer": ["0"],
        "hot_plate_temp": ["110"],
        "hot_plate_temp_initial_layer": ["110"],
        "instantiation": "false",
        "name": "Generic PC template",
        "nozzle_temperature": ["280"],
        "nozzle_temperature_initial_layer": ["270"],
        "nozzle_temperature_range_high": ["290"],
        "nozzle_temperature_range_low": ["260"],
        "overhang_fan_speed": ["60"],
        "overhang_fan_threshold": ["25%"],
        "reduce_fan_stop_start_freq": ["1"],
        "required_nozzle_HRC": ["3"],
        "slow_down_for_layer_cooling": ["1"],
        "slow_down_layer_time": ["2"],
        "slow_down_min_speed": ["20"],
        "temperature_vitrification": ["120"],
        "textured_plate_temp": ["110"],
        "textured_plate_temp_initial_layer": ["110"],
        "type": "filament",
    },
    "PETG": {
        "activate_air_filtration": ["0"],
        "chamber_temperatures": ["0"],
        "close_fan_the_first_x_layers": ["3"],
        "compatible_printers": [],
        "complete_print_exhaust_fan_speed": ["70"],
        "cool_plate_temp": ["60"],
        "cool_plate_temp_initial_layer": ["60"],
        "during_print_exhaust_fan_speed": ["70"],
        "eng_plate_temp": ["0"],
        "eng_plate_temp_initial_layer": ["0"],
        "fan_cooling_layer_time": ["20"],
        "fan_max_speed": ["100"],
        "fan_min_speed": ["20"],
        "filament_cost": ["30"],
        "filament_density": ["1.27"],
        "filament_deretraction_speed": ["nil"],
        "filament_diameter": ["1.75"],
        "filament_end_gcode": ["; filament end gcode \nM106 P3 S0\n"],
        "filament_flow_ratio": ["1"],
        "filament_is_support": ["0"],
        "filament_max_volumetric_speed": ["25"],
        "filament_minimal_purge_on_wipe_tower": ["15"],
        "filament_retract_before_wipe": ["nil"],
        "filament_retract_restart_extra": ["nil"],
        "filament_retract_when_changing_layer": ["nil"],
        "filament_retraction_length": ["nil"],
        "filament_retraction_minimum_travel": ["nil"],
        "filament_retraction_speed": ["nil"],
        "filament_settings_id": [""],
        "filament_soluble": ["0"],
        "filament_start_gcode": ["; filament start gcode\n{if (bed_temperature[current_extruder] >45)||(bed_temperature_initial_layer[current_extruder] >45)}M106 P3 S180\n{elsif (bed_temperature[current_extruder] >50)||(bed_temperature_initial_layer[current_extruder] >50)}M106 P3 S255\n{endif};Prevent PLA from jamming\n\n{if activate_air_filtration[current_extruder] && support_air_filtration}\nM106 P3 S{during_print_exhaust_fan_speed_num[current_extruder]} \n{endif}"],
        "filament_type": ["PETG"],
        "filament_vendor": ["Generic"],
        "filament_wipe": ["nil"],
        "filament_wipe_distance": ["nil"],
        "filament_z_hop": ["nil"],
        "filament_z_hop_types": ["nil"],
        "full_fan_speed_layer": ["0"],
        "hot_plate_temp": ["80"],
        "hot_plate_temp_initial_layer": ["80"],
        "instantiation": "false",
        "name": "Generic PET template",
        "nozzle_temperature": ["255"],
        "nozzle_temperature_initial_layer": ["255"],
        "nozzle_temperature_range_high": ["260"],
        "nozzle_temperature_range_low": ["220"],
        "overhang_fan_speed": ["100"],
        "overhang_fan_threshold": ["95%"],
        "reduce_fan_stop_start_freq": ["1"],
        "required_nozzle_HRC": ["3"],
        "slow_down_for_layer_cooling": ["1"],
        "slow_down_layer_time": ["8"],
        "slow_down_min_speed": ["10"],
        "temperature_vitrification": ["70"],
        "textured_plate_temp": ["80"],
        "textured_plate_temp_initial_layer": ["80"],
        "type": "filament",
    },
    "PLA": {
        "activate_air_filtration": ["0"],
        "additional_cooling_fan_speed": ["70"],
        "chamber_temperatures": ["0"],
        "close_fan_the_first_x_layers": ["1"],
        "compatible_printers": [],
        "complete_print_exhaust_fan_speed": ["70"],
        "cool_plate_temp": ["35"],
        "cool_plate_temp_initial_layer": ["35"],
        "during_print_exhaust_fan_speed": ["70"],
        "eng_plate_temp": ["0"],
        "eng_plate_temp_initial_layer": ["0"],
        "fan_cooling_layer_time": ["100"],
        "fan_max_speed": ["100"],
        "fan_min_speed": ["100"],
        "filament_cost": ["20"],
        "filament_density": ["1.24"],
        "filament_deretraction_speed": ["nil"],
        "filament_diameter": ["1.75"],
        "filament_end_gcode": ["; filament end gcode \nM106 P3 S0\n"],
        "filament_flow_ratio": ["1"],
        "filament_is_support": ["0"],
        "filament_max_volumetric_speed": ["12"],
        "filament_minimal_purge_on_wipe_tower": ["15"],
        "filament_retract_before_wipe": ["nil"],
        "filament_retract_restart_extra": ["nil"],
        "filament_retract_when_changing_layer": ["nil"],
        "filament_retraction_length": ["nil"],
        "filament_retraction_minimum_travel": ["nil"],
        "filament_retraction_speed": ["nil"],
        "filament_settings_id": [""],
        "filament_soluble": ["0"],
        "filament_start_gcode": ["; filament start gcode\n{if  (bed_temperature[current_extruder] >45)||(bed_temperature_initial_layer[current_extruder] >45)}M106 P3 S255\n{elsif(bed_temperature[current_extruder] >35)||(bed_temperature_initial_layer[current_extruder] >35)}M106 P3 S180\n{endif}\n\n{if activate_air_filtration[current_extruder] && support_air_filtration}\nM106 P3 S{during_print_exhaust_fan_speed_num[current_extruder]} \n{endif}"],
        "filament_type": ["PLA"],
        "filament_vendor": ["Generic"],
        "filament_wipe": ["nil"],
        "filament_wipe_distance": ["nil"],
        "filament_z_hop": ["nil"],
        "filament_z_hop_types": ["nil"],
        "full_fan_speed_layer": ["0"],
        "hot_plate_temp": ["55"],
        "hot_plate_temp_initial_layer": ["55"],
        "instantiation": "false",
        "name": "Generic PLA template",
        "nozzle_temperature": ["220"],
        "nozzle_temperature_initial_layer": ["220"],
        "nozzle_temperature_range_high": ["240"],
        "nozzle_temperature_range_low": ["190"],
        "overhang_fan_speed": ["100"],
        "overhang_fan_threshold": ["50%"],
        "reduce_fan_stop_start_freq": ["1"],
        "required_nozzle_HRC": ["3"],
        "slow_down_for_layer_cooling": ["1"],
        "slow_down_layer_time": ["4"],
        "slow_down_min_speed": ["20"],
        "temperature_vitrification": ["55"],
        "textured_plate_temp": ["55"],
        "textured_plate_temp_initial_layer": ["55"],
        "type": "filament",
    },
    "PPA-CF": {
        "activate_air_filtration": ["1"],
        "chamber_temperatures": ["0"],
        "close_fan_the_first_x_layers": ["3"],
        "compatible_printers": [],
        "complete_print_exhaust_fan_speed": ["70"],
        "cool_plate_temp": ["0"],
        "cool_plate_temp_initial_layer": ["0"],
        "during_print_exhaust_fan_speed": ["70"],
        "eng_plate_temp": ["100"],
        "eng_plate_temp_initial_layer": ["100"],
        "fan_cooling_layer_time": ["5"],
        "fan_max_speed": ["30"],
        "fan_min_speed": ["10"],
        "filament_cost": ["20"],
        "filament_density": ["1.17"],
        "filament_deretraction_speed": ["nil"],
        "filament_diameter": ["1.75"],
        "filament_end_gcode": ["; filament end gcode \nM106 P3 S0\n"],
        "filament_flow_ratio": ["0.96"],
        "filament_is_support": ["0"],
        "filament_max_volumetric_speed": ["8"],
        "filament_minimal_purge_on_wipe_tower": ["15"],
        "filament_retract_before_wipe": ["nil"],
        "filament_retract_restart_extra": ["nil"],
        "filament_retract_when_changing_layer": ["nil"],
        "filament_retraction_length": ["nil"],
        "filament_retraction_minimum_travel": ["nil"],
        "filament_retraction_speed": ["nil"],
        "filament_settings_id": [""],
        "filament_soluble": ["0"],
        "filament_start_gcode": ["; Filament gcode\n{if activate_air_filtration[current_extruder] && support_air_filtration}\nM106 P3 S{during_print_exhaust_fan_speed_num[current_extruder]} \n{endif}"],
        "filament_type": ["PPA-CF"],
        "filament_vendor": ["Generic"],
        "filament_wipe": ["nil"],
        "filament_wipe_distance": ["nil"],
        "filament_z_hop": ["nil"],
        "filament_z_hop_types": ["nil"],
        "full_fan_speed_layer": ["0"],
        "hot_plate_temp": ["100"],
        "hot_plate_temp_initial_layer": ["100"],
        "instantiation": "false",
        "name": "Generic PPA template",
        "nozzle_temperature": ["290"],
        "nozzle_temperature_initial_layer": ["290"],
        "nozzle_temperature_range_high": ["320"],
        "nozzle_temperature_range_low": ["280"],
        "overhang_fan_speed": ["40"],
        "overhang_fan_threshold": ["0%"],
        "reduce_fan_stop_start_freq": ["0"],
        "required_nozzle_HRC": ["40"],
        "slow_down_for_layer_cooling": ["1"],
        "slow_down_layer_time": ["2"],
        "slow_down_min_speed": ["20"],
        "temperature_vitrification": ["210"],
        "textured_plate_temp": ["100"],
        "textured_plate_temp_initial_layer": ["100"],
        "type": "filament",
    },
    "PPS": {
        "activate_air_filtration": ["0"],
        "chamber_temperatures": ["60"],
        "close_fan_the_first_x_layers": ["3"],
        "compatible_printers": [],
        "complete_print_exhaust_fan_speed": ["70"],
        "cool_plate_temp": ["0"],
        "cool_plate_temp_initial_layer": ["0"],
        "during_print_exhaust_fan_speed": ["70"],
        "eng_plate_temp": ["110"],
        "eng_plate_temp_initial_layer": ["110"],
        "fan_cooling_layer_time": ["5"],
        "fan_max_speed": ["50"],
        "fan_min_speed": ["0"],
        "filament_cost": ["0"],
        "filament_density": ["1.36"],
        "filament_deretraction_speed": ["nil"],
        "filament_diameter": ["1.75"],
        "filament_end_gcode": ["; filament end gcode \nM106 P3 S0\n"],
        "filament_flow_ratio": ["0.96"],
        "filament_is_support": ["0"],
        "filament_max_volumetric_speed": ["4"],
        "filament_minimal_purge_on_wipe_tower": ["15"],
        "filament_retract_before_wipe": ["nil"],
        "filament_retract_restart_extra": ["nil"],
        "filament_retract_when_changing_layer": ["nil"],
        "filament_retraction_length": ["nil"],
        "filament_retraction_minimum_travel": ["nil"],
        "filament_retraction_speed": ["nil"],
        "filament_settings_id": [""],
        "filament_soluble": ["0"],
        "filament_start_gcode": ["; Filament gcode\n{if activate_air_filtration[current_extruder] && support_air_filtration}\nM106 P3 S{during_print_exhaust_fan_speed_num[current_extruder]} \n{endif}"],
        "filament_type": ["PPS"],
        "filament_vendor": ["Generic"],
        "filament_wipe": ["nil"],
        "filament_wipe_distance": ["nil"],
        "filament_z_hop": ["nil"],
        "filament_z_hop_types": ["nil"],
        "full_fan_speed_layer": ["0"],
        "hot_plate_temp": ["110"],
        "hot_plate_temp_initial_layer": ["110"],
        "instantiation": "false",
        "name": "Generic PPS template",
        "nozzle_temperature": ["320"],
        "nozzle_temperature_initial_layer": ["320"],
        "nozzle_temperature_range_high": ["340"],
        "nozzle_temperature_range_low": ["300"],
        "overhang_fan_speed": ["30"],
        "overhang_fan_threshold": ["0%"],
        "reduce_fan_stop_start_freq": ["0"],
        "required_nozzle_HRC": ["3"],
        "slow_down_for_layer_cooling": ["1"],
        "slow_down_layer_time": ["2"],
        "slow_down_min_speed": ["10"],
        "temperature_vitrification": ["125"],
        "textured_plate_temp": ["110"],
        "textured_plate_temp_initial_layer": ["110"],
        "type": "filament",
    },
    "PVA": {
        "activate_air_filtration": ["0"],
        "additional_cooling_fan_speed": ["70"],
        "chamber_temperatures": ["0"],
        "close_fan_the_first_x_layers": ["1"],
        "compatible_printers": [],
        "complete_print_exhaust_fan_speed": ["70"],
        "cool_plate_temp": ["45"],
        "cool_plate_temp_initial_layer": ["45"],
        "during_print_exhaust_fan_speed": ["70"],
        "eng_plate_temp": ["0"],
        "eng_plate_temp_initial_layer": ["0"],
        "fan_cooling_layer_time": ["100"],
        "fan_max_speed": ["100"],
        "fan_min_speed": ["100"],
        "filament_cost": ["20"],
        "filament_density": ["1.24"],
        "filament_deretraction_speed": ["nil"],
        "filament_diameter": ["1.75"],
        "filament_end_gcode": ["; filament end gcode \nM106 P3 S0\n"],
        "filament_flow_ratio": ["1"],
        "filament_is_support": ["1"],
        "filament_max_volumetric_speed": ["15"],
        "filament_minimal_purge_on_wipe_tower": ["15"],
        "filament_retract_before_wipe": ["nil"],
        "filament_retract_restart_extra": ["nil"],
        "filament_retract_when_changing_layer": ["nil"],
        "filament_retraction_length": ["nil"],
        "filament_retraction_minimum_travel": ["nil"],
        "filament_retraction_speed": ["nil"],
        "filament_settings_id": [""],
        "filament_soluble": ["1"],
        "filament_start_gcode": ["; filament start gcode\n{if  (bed_temperature[current_extruder] >45)||(bed_temperature_initial_layer[current_extruder] >45)}M106 P3 S255\n{elsif(bed_temperature[current_extruder] >35)||(bed_temperature_initial_layer[current_extruder] >35)}M106 P3 S180\n{endif}\n\n{if activate_air_filtration[current_extruder] && support_air_filtration}\nM106 P3 S{during_print_exhaust_fan_speed_num[current_extruder]} \n{endif}"],
        "filament_type": ["PVA"],
        "filament_vendor": ["Generic"],
        "filament_wipe": ["nil"],
        "filament_wipe_distance": ["nil"],
        "filament_z_hop": ["nil"],
        "filament_z_hop_types": ["nil"],
        "full_fan_speed_layer": ["0"],
        "hot_plate_temp": ["55"],
        "hot_plate_temp_initial_layer": ["55"],
        "instantiation": "false",
        "name": "Generic PVA template",
        "nozzle_temperature": ["220"],
        "nozzle_temperature_initial_layer": ["220"],
        "nozzle_temperature_range_high": ["240"],
        "nozzle_temperature_range_low": ["190"],
        "overhang_fan_speed": ["100"],
        "overhang_fan_threshold": ["50%"],
        "reduce_fan_stop_start_freq": ["1"],
        "required_nozzle_HRC": ["3"],
        "slow_down_for_layer_cooling": ["1"],
        "slow_down_layer_time": ["4"],
        "slow_down_min_speed": ["50"],
        "temperature_vitrification": ["55"],
        "textured_plate_temp": ["55"],
        "textured_plate_temp_initial_layer": ["55"],
        "type": "filament",
    },
    "SBS": {
        "activate_air_filtration": ["0"],
        "additional_cooling_fan_speed": ["40"],
        "chamber_temperatures": ["0"],
        "close_fan_the_first_x_layers": ["3"],
        "compatible_printers": [],
        "complete_print_exhaust_fan_speed": ["70"],
        "cool_plate_temp": ["70"],
        "cool_plate_temp_initial_layer": ["70"],
        "during_print_exhaust_fan_speed": ["70"],
        "eng_plate_temp": ["70"],
        "eng_plate_temp_initial_layer": ["70"],
        "fan_cooling_layer_time": ["100"],
        "fan_max_speed": ["40"],
        "fan_min_speed": ["0"],
        "filament_cost": ["15"],
        "filament_density": ["1.02"],
        "filament_deretraction_speed": ["nil"],
        "filament_diameter": ["1.75"],
        "filament_end_gcode": ["; filament end gcode \nM106 P3 S0\n"],
        "filament_flow_ratio": ["0.98"],
        "filament_is_support": ["0"],
        "filament_max_volumetric_speed": ["23"],
        "filament_minimal_purge_on_wipe_tower": ["15"],
        "filament_retract_before_wipe": ["nil"],
        "filament_retract_restart_extra": ["nil"],
        "filament_retract_when_changing_layer": ["nil"],
        "filament_retraction_length": ["nil"],
        "filament_retraction_minimum_travel": ["nil"],
        "filament_retraction_speed": ["nil"],
        "filament_settings_id": [""],
        "filament_soluble": ["0"],
        "filament_start_gcode": ["; filament start gcode\n{if  (bed_temperature[current_extruder] >45)||(bed_temperature_initial_layer[current_extruder] >45)}M106 P3 S255\n{elsif(bed_temperature[current_extruder] >35)||(bed_temperature_initial_layer[current_extruder] >35)}M106 P3 S180\n{endif}\n\n{if activate_air_filtration[current_extruder] && support_air_filtration}\nM106 P3 S{during_print_exhaust_fan_speed_num[current_extruder]} \n{endif}"],
        "filament_type": ["SBS"],
        "filament_vendor": ["Generic"],
        "filament_wipe": ["nil"],
        "filament_wipe_distance": ["nil"],
        "filament_z_hop": ["nil"],
        "filament_z_hop_types": ["nil"],
        "full_fan_speed_layer": ["0"],
        "hot_plate_temp": ["5705"],
        "hot_plate_temp_initial_layer": ["70"],
        "instantiation": "false",
        "name": "Generic SBS template",
        "nozzle_temperature": ["235"],
        "nozzle_temperature_initial_layer": ["235"],
        "nozzle_temperature_range_high": ["250"],
        "nozzle_temperature_range_low": ["215"],
        "overhang_fan_speed": ["100"],
        "overhang_fan_threshold": ["50%"],
        "reduce_fan_stop_start_freq": ["0"],
        "required_nozzle_HRC": ["3"],
        "slow_down_for_layer_cooling": ["1"],
        "slow_down_layer_time": ["4"],
        "slow_down_min_speed": ["20"],
        "temperature_vitrification": ["70"],
        "textured_plate_temp": ["70"],
        "textured_plate_temp_initial_layer": ["70"],
        "type": "filament",
    },
    "TPU": {
        "activate_air_filtration": ["0"],
        "additional_cooling_fan_speed": ["70"],
        "chamber_temperatures": ["0"],
        "close_fan_the_first_x_layers": ["1"],
        "compatible_printers": [],
        "complete_print_exhaust_fan_speed": ["70"],
        "cool_plate_temp": ["30"],
        "cool_plate_temp_initial_layer": ["30"],
        "during_print_exhaust_fan_speed": ["70"],
        "eng_plate_temp": ["30"],
        "eng_plate_temp_initial_layer": ["30"],
        "fan_cooling_layer_time": ["100"],
        "fan_max_speed": ["100"],
        "fan_min_speed": ["100"],
        "filament_cost": ["20"],
        "filament_density": ["1.24"],
        "filament_deretraction_speed": ["nil"],
        "filament_diameter": ["1.75"],
        "filament_end_gcode": ["; filament end gcode \nM106 P3 S0\n"],
        "filament_flow_ratio": ["1"],
        "filament_is_support": ["0"],
        "filament_max_volumetric_speed": ["15"],
        "filament_minimal_purge_on_wipe_tower": ["15"],
        "filament_retract_before_wipe": ["nil"],
        "filament_retract_restart_extra": ["nil"],
        "filament_retract_when_changing_layer": ["nil"],
        "filament_retraction_length": ["0.4"],
        "filament_retraction_minimum_travel": ["nil"],
        "filament_retraction_speed": ["nil"],
        "filament_settings_id": [""],
        "filament_soluble": ["0"],
        "filament_start_gcode": ["; filament start gcode\n{if  (bed_temperature[current_extruder] >35)||(bed_temperature_initial_layer[current_extruder] >35)}M106 P3 S255\n{elsif(bed_temperature[current_extruder] >30)||(bed_temperature_initial_layer[current_extruder] >30)}M106 P3 S180\n{endif}\n\n{if activate_air_filtration[current_extruder] && support_air_filtration}\nM106 P3 S{during_print_exhaust_fan_speed_num[current_extruder]} \n{endif}"],
        "filament_type": ["TPU"],
        "filament_vendor": ["Generic"],
        "filament_wipe": ["nil"],
        "filament_wipe_distance": ["nil"],
        "filament_z_hop": ["nil"],
        "filament_z_hop_types": ["nil"],
        "full_fan_speed_layer": ["0"],
        "hot_plate_temp": ["35"],
        "hot_plate_temp_initial_layer": ["35"],
        "instantiation": "false",
        "name": "Generic TPU template",
        "nozzle_temperature": ["240"],
        "nozzle_temperature_initial_layer": ["240"],
        "nozzle_temperature_range_high": ["250"],
        "nozzle_temperature_range_low": ["200"],
        "overhang_fan_speed": ["100"],
        "overhang_fan_threshold": ["95%"],
        "reduce_fan_stop_start_freq": ["1"],
        "required_nozzle_HRC": ["3"],
        "slow_down_for_layer_cooling": ["1"],
        "slow_down_layer_time": ["8"],
        "slow_down_min_speed": ["10"],
        "temperature_vitrification": ["35"],
        "textured_plate_temp": ["35"],
        "textured_plate_temp_initial_layer": ["35"],
        "type": "filament",
    },
}

# Default material type for unknown filaments (falls back to PLA)
DEFAULT_MATERIAL = "PLA"

# List of all standard filament keys
STANDARD_FILAMENT_KEYS = set(FILAMENT_MATERIAL_DEFAULTS[DEFAULT_MATERIAL].keys())

__all__ = [
    "FILAMENT_MATERIAL_DEFAULTS",
    "DEFAULT_MATERIAL",
    "STANDARD_FILAMENT_KEYS",
]